import * as fs from 'fs/promises';
import * as path from 'path';
import Handlebars from 'handlebars';
import { Fragment, MergeResult, ResolvedModule } from '../types';
import { LAYER_ORDER } from './resolver';

/**
 * Reads all files of a given fragmentType (e.g. "rules", "commands") from
 * each module directory and returns them as Fragment objects.
 */
export async function collectFragments(
  modules: ResolvedModule[],
  fragmentType: string
): Promise<Fragment[]> {
  const fragments: Fragment[] = [];

  for (const mod of modules) {
    const fragDir = path.join(mod.path, fragmentType);
    let files: string[];
    try {
      files = await fs.readdir(fragDir);
    } catch {
      // directory doesn't exist for this module — that's fine
      continue;
    }

    for (const file of files) {
      const filePath = path.join(fragDir, file);
      const stat = await fs.stat(filePath);
      if (!stat.isFile()) continue;

      const raw = await fs.readFile(filePath, 'utf-8');
      const content = interpolate(raw, mod.variables, {
        moduleName: mod.manifest.name,
        filename: `${fragmentType}/${file}`,
      });

      fragments.push({
        type: fragmentType,
        filename: file,
        content,
        layer: mod.manifest.layer,
        moduleName: mod.manifest.name,
      });
    }
  }

  return fragments;
}

/**
 * For each filename, keeps the fragment from the highest-layer module.
 * When layers are equal, the later entry in the array wins (preserves order).
 */
export function mergeFragments(fragments: Fragment[]): Record<string, Fragment> {
  const result: Record<string, Fragment> = {};

  for (const fragment of fragments) {
    const key = `${fragment.type}/${fragment.filename}`;
    const existing = result[key];
    if (!existing) {
      result[key] = fragment;
    } else {
      const existingOrder = LAYER_ORDER[existing.layer] ?? 0;
      const newOrder = LAYER_ORDER[fragment.layer] ?? 0;
      if (newOrder >= existingOrder) {
        result[key] = fragment;
      }
    }
  }

  return result;
}

/**
 * Interpolates {{variable}} placeholders in content using Handlebars.
 */
export function interpolate(
  content: string,
  variables: Record<string, unknown>,
  context?: { moduleName: string; filename: string }
): string {
  try {
    const template = Handlebars.compile(content, { noEscape: true });
    return template(variables);
  } catch (err) {
    const location = context ? `${context.moduleName}/${context.filename}` : 'unknown';
    const message = err instanceof Error ? err.message : String(err);
    throw new Error(`Failed to interpolate ${location}: ${message}`);
  }
}

/**
 * Builds the final CLAUDE.md by concatenating all claude-md/ sections from
 * all modules in layer order (all sections included, not winner-takes-all),
 * with a generated project header at the top.
 */
export async function buildClaudeMd(
  modules: ResolvedModule[],
  projectName: string,
  projectDescription?: string
): Promise<string> {
  const lines: string[] = [];

  // Project header
  lines.push(`# ${projectName}`);
  if (projectDescription) {
    lines.push('');
    lines.push(projectDescription);
  }
  lines.push('');
  lines.push(
    '> This file was generated by [stackweave](https://github.com/stackweave/stackweave). Do not edit by hand.'
  );
  lines.push('');

  // Collect all claude-md sections in layer order (modules are already sorted)
  for (const mod of modules) {
    const claudeMdDir = path.join(mod.path, 'claude-md');
    let files: string[];
    try {
      files = await fs.readdir(claudeMdDir);
    } catch {
      continue;
    }

    // Sort files within a module alphabetically for determinism
    files.sort();

    for (const file of files) {
      const filePath = path.join(claudeMdDir, file);
      const stat = await fs.stat(filePath);
      if (!stat.isFile()) continue;

      const raw = await fs.readFile(filePath, 'utf-8');
      const content = interpolate(raw, mod.variables, {
        moduleName: mod.manifest.name,
        filename: `claude-md/${file}`,
      });
      lines.push(content.trimEnd());
      lines.push('');
    }
  }

  return lines.join('\n');
}

/**
 * Orchestrates fragment collection, merging, and CLAUDE.md assembly for all
 * supported fragment types.
 */
export async function buildMergeResult(
  modules: ResolvedModule[],
  projectName: string,
  projectDescription?: string
): Promise<MergeResult> {
  const fragmentTypes = ['rules', 'commands', 'guides', 'agents'];
  const allFragments: Fragment[] = [];

  for (const type of fragmentTypes) {
    const collected = await collectFragments(modules, type);
    allFragments.push(...collected);
  }

  const mergedFragments = mergeFragments(allFragments);
  const claudeMd = await buildClaudeMd(modules, projectName, projectDescription);

  return {
    fragments: mergedFragments,
    claudeMdSections: [claudeMd],
  };
}
